apiVersion: v2
name: plex-wrapper
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: plex-media-server
    repository: https://plexinc.github.io/pms-docker
    version: 0.1.8