apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  # Project description
  description: ArgoCD Bootstrap apps

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'