ingress-nginx:
  controller:
    replicaCount: 1
    ingressClassResource:
      default: true
    extraArgs:
      enable-ssl-passthrough: ""
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

