ingress-nginx:
  controller:
    replicaCount: 1
    ingressClassResource:
      default: true
    extraArgs:
      enable-ssl-passthrough: ""
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      clusterIP: "10.30.151.15"

