apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: benchmark-app-plex-media-server-application
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: plex
  project: benchmark-apps
  source:
    path: argocd/apps-manifests/benchmark-app-plex-media-server
    repoURL: 'https://github.com/rodriwp/tfm'
    helm:
      valueFiles:
      - 'values.yaml'
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true