apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cluster-resources-cert-manager
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  project: cluster-resources
  source:
    path: argocd/apps-manifests/cluster-resources-cert-manager
    repoURL: 'https://github.com/rodriwp/tfm'
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true