apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: monitoring-kube-prometheus-stack-application
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: observability
  source:
    path: apps-manifests/monitoring-kube-prometheus-stack
    repoURL: 'https://github.com/rodriwp/tfm'
    helm:
      releaseName: observability
      skipCrds: true
      valueFiles:
      - 'values.yaml'
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true