apiVersion: v2
name: kube-prometheus-stack-wrapper
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: cost-analyzer
    repository: https://kubecost.github.io/cost-analyzer/
    version: 1.108.1