cost-analyzer:
  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "10m"
        memory: "55Mi"
      #limits:
      #  cpu: "100m"
      #  memory: "256Mi"

  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model
    imagePullPolicy: Always
    warmCache: true
    etl: true
    # The total number of days the ETL pipelines will build
    # Set to 0 to disable daily ETL (not recommended)
    etlDailyStoreDurationDays: 120
    maxQueryConcurrency: 5
    # utcOffset represents a timezone in hours and minutes east (+) or west (-)
    # of UTC, itself, which is defined as +00:00.
    # See the tz database of timezones to look up your local UTC offset:
    # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    utcOffset: "+00:00"
    resources:
      requests:
        cpu: "200m"
        memory: "55Mi"
      #limits:
      #  cpu: "800m"
      #  memory: "256Mi"
  networkCosts:
    enabled: true
    config:
      destinations:
        # In Zone contains a list of address/range that will be
        # classified as in zone.
        in-zone:
          # Loopback Addresses in "IANA IPv4 Special-Purpose Address Registry"
          - "127.0.0.0/8"
          # IPv4 Link Local Address Space
          - "169.254.0.0/16"
          # Private Address Ranges in RFC-1918
          - "172.16.0.0/12"
          - "192.168.0.0/16"


        # In Region contains a list of address/range that will be
        # classified as in region. This is synonymous with cross
        # zone traffic, where the regions between source and destinations
        # are the same, but the zone is different.
        in-region:
          - "10.30.128.0/20"
          - "10.30.144.0/20"
          - "10.30.160.0/20"

        # Cross Region contains a list of address/range that will be
        # classified as non-internet egress from one region to another.
        cross-region: [ ]

        # Direct Classification specifically maps an ip address or range
        # to a region (required) and/or zone (optional). This classification
        # takes priority over in-zone, in-region, and cross-region configurations.
        internet:
          - "10.30.174.96"
        direct-classification:
         - region: "eu-central-1"
           zone: "eu-central-1a"
           ips:
             - "10.30.0.0/20"
         - region: "eu-central-1"
           zone: "eu-central-1b"
           ips:
             - "10.30.16.0/20"
         - region: "eu-central-1"
           zone: "eu-central-1c"
           ips:
             - "10.30.32.0/20"
      services:
        amazon-web-services: true

